[book]
title = "CE7453 Numerical Algorithms Notes"
authors = ["Your Name"]
language = "zh-CN"

[output.html]
default-theme = "light"
additional-css = ["katex-fix.css"]
additional-js = ["custom.js"]
git-repository-url = "https://github.com/Yikai-Liao/ce7453-notes"
edit-url-template = "https://github.com/Yikai-Liao/ce7453-notes/edit/main/{path}"

[preprocessor.katex]
after = ["links"]
# KaTeX options.
output = "html"
leqno = false
fleqn = false
throw-on-error = true
error-color = "#cc0000"
min-rule-thickness = -1.0
max-size = "Infinity"
max-expand = 1000
trust = false
# Extra options.
no-css = false
include-src = false
block-delimiter = { left = "$$", right = "$$" }
inline-delimiter = { left = "$", right = "$" }
pre-render = true

[output.pdf]